name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip actual publish to registry)'
        type: boolean
        default: true

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'unstoppablecarl/static-records'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for npm provenance
    # Use Release environment for deployment protection
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: npm stage publish --access public --provenance${{ (github.event_name == 'workflow_dispatch' && inputs.dry_run) && ' --dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
